### PR TITLE
Next reviews in ...

### PR DESCRIPTION
**Pull request by DJTB**
Hey, I use the companion a lot, but whenever there are no reviews I'll often go to WK dashboard just to see the countdown timer. 

So, I added a countdown into the companion dropdown.
Would love to see this integrated so I can use the official extension instead of my local unpacked one.

### CODE REVIEW

**Comment by DJTB** [comment]
piskohe

**Comment by agarny** [comment]
I was just about to implement something similar myself, but I thought I would check the official repo first and... glad that I did! It looks good to me, so I think I am going to use it until then.

**Comment by DJTB** [comment]
No response from @naei still so it might take some time to hit a chrome store update. Feel free to use the fork ^^

**Comment by agarny** [comment]
This is what I am doing and it's working very nicely. Thanks for your work.

**Comment by naei** [comment]
Thank you for your work DJTB! I check that everything's OK and I will probably update the Chrome extension very shortly.

**Comment by naei** [comment]
Hey guys. As most of people don't need this information if they have remaining reviews, I made few changes to display the countdown timer only when there is no remaining reviews (and it help to keep a lightweight interface).

screenshot from 2015-12-28 17 07 44

Can you check the [development branch](https://github.com/naei/wanikani-companion/tree/development) and tell me if everything's working properly please (I have a lot of reviews to do, so I'm not able to test this feature right now) ?

**Comment by agarny** [comment]
Having no reviews left, I can confirm that I am getting something like in your screenshot.

Otherwise, you might want to have something that reads something like:

`No reviews left.
Your next review is in 31 minutes.`

or

`No reviews left.
Your next 5 reviews are in 31 minutes.`

Indeed, I personally find it useful to be told how many reviews are coming up.

**Comment by naei** [comment]
The WaniKani API allow to get the next review date and the number of reviews for the next hour / day, but not the number of reviews for the next review date. We can display something like "your next review is in 31 minutes", or "5 reviews are coming within the next hour" but not "Your next 5 reviews are in 31 minutes", so the first solution is a better choice for most people.

I updated the text based on your suggestion (thank you for this). I have kept only the first part in order to nicely fit the content within the div.

**Comment by DJTB** [comment]
I'll test it through today and let you know.

**Comment by DJTB** [comment]
So far so good, I don't foresee any problems with these changes. Feel free to close the PR since you integrated the changes yourself.

**Comment by naei** [comment]
I only changed the design, being based on your fork. Thank you ;)

**Comment by DJTB** [comment]
Awesome, you're welcome :)

**Comment by agarny** [comment]
Thanks indeed, it looks good.

**Comment by agarny** [comment]
I have just noticed a minor thing that could be improved. Right now, if I check my next review, it reads:

```
No reviews left.
Next review in 2
hours.
```

It's clearly fine (and correct), but it would be (slightly) better if it read:

```
No reviews left.
Next review in
2 hours.
```

So that all the user has to do is to 'concentrate' on the last line...

**Comment by naei** [comment]
Done :)

**Comment by agarny** [comment]
Thanks a lot! :)

**Pull request closed without merging**
